### ISSUE TITLE
npm ERR! code E404

### ISSUE THREAD

**Issue by aboodh95** [scottdurow/cdsify#3]
Hi,

Once i'm doing npx node-cds-gen [tennant] [environment] with my environments details, I'm getting this error 
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/node-cds-gen - Not found
npm ERR! 404
npm ERR! 404  'node-cds-gen@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abodh\AppData\Roaming\npm-cache\_logs\2020-05-05T21_13_08_353Z-debug.log
Install for [ 'node-cds-gen@latest' ] failed with code 1`
[2020-05-05T21_13_08_353Z-debug.log](https://github.com/scottdurow/cdsify/files/4583647/2020-05-05T21_13_08_353Z-debug.log)

**Comment by scottdurow** [comment]
It is actually:
```npx node-cds-auth [environment url]```

**Comment by scottdurow** [comment]
E.g. 
```npx node-cds-auth org.crm.dynamics.com```

**Comment by aboodh95** [comment]
@scottdurow ,
Thanks, that resolved the issue
