### ISSUE TITLE
Odataify : Navigation properties should be based on SchemaName

### ISSUE THREAD

**Issue by drivardxrm** [scottdurow/cdsify#7]
Hi @scottdurow , 
First of all, thank you so much for this amazing package. Once again you are leading the parade ;).

I found a small glitch with the Odataify function when trying to declare lookups (navigation) on an entity.

The early bound properties on a given record are based on the LogicalName but the Odata statement needs to be bound on the SchemaName.
There is no problems if the schema name is all lowercase (thus LogicalName = SchemaName), but when there are uppercase characters in the schema name, the call to Odataify gives an error.

![image](https://user-images.githubusercontent.com/38399134/95018788-ddd6bf00-062f-11eb-8a4a-4636a2d214da.png)

Expected Odata statement:
![image](https://user-images.githubusercontent.com/38399134/95018958-a9173780-0630-11eb-856c-915cefbfb834.png)

![image](https://user-images.githubusercontent.com/38399134/95019181-eaf4ad80-0631-11eb-841d-4980e01dd590.png)

![image](https://user-images.githubusercontent.com/38399134/95019168-dca69180-0631-11eb-835d-b3b3ba5bb57e.png)

![image](https://user-images.githubusercontent.com/38399134/95019502-beda2c00-0633-11eb-842c-aee2739968b1.png)

The source of the error seems to be on this call:
![image](https://user-images.githubusercontent.com/38399134/95019614-50499e00-0634-11eb-91bb-ec47e9e88c5a.png)

I will try to submit a PR with a solution.

Thanks!

**Comment by scottdurow** [comment]
Thank you for reporting this issue!

Your analysis seems spot on - the solution does seem to be to perform a case insensitive search of the navigation properties.

All the unit tests/integration tests at the moment are using the out of the box navigation properties that have lowercase navigation properties - what is interesting is that some of the schema names do show as pascal case but in the webapi metadata they are still lowercase!

I think I have a fix and some unit tests.

**Comment by scottdurow** [comment]
@drivardxrm This fix should get you up and running with your custom entity lookups - any chance you could grab 1.0.5 and have a go?
